@extends('layouts.app')
@section('content')

<div class="getting-started-text text-size-lg" style="margin-top:6rem;padding-top:3rem; padding-bottom:4rem; margin-bottom:2rem;background:#001F3F; width: 100%;">
    <h2 style="font-weight:600;color:white;" class="getting-started-text text-center text-size-lg">Our <span class="havvest" style="color:green;">JAP Scholarship Programs</span></h2>
    <p style="color:white;font-family: 'Montserrat', sans-serif !important; margin-top:2rem; width:90%; margin-left: auto; margin-right: auto; text-align:center;">
        We appreciate your interest in applying for the JAP Scholarship. Before proceeding with your application, we highly encourage you to thoroughly review the scholarship rules outlined below. These rules are designed to ensure fairness and transparency throughout the application process.</p>


</div>


<main class="content" style="width: 100%; flex-basis: 100%; padding: 2rem;">
    <div class="entry-header">
      <h1 class="entry-title" style="padding-top: 3rem; margin-top:1rem; text-align: center; color:black; padding-bottom: 3rem; font-size: 2rem;"> JAP Scholarship Rules</h1>
    </div>
    <div class="entry-content">
      <p style="font-size: 1rem;"><strong>By applying for a scholarship, you agree to be bound by these Scholarship Rules, and you understand that any violation of these Rules shall result in your disqualification from the scholarship. If you do not agree to these Scholarship Rules, you may not apply for, nor accept, a scholarship</strong></p>
      <p style="font-size: 1rem;">The JAP Scholarship Inc (&#8220;JAP Scholarship&#8221;) Terms of Use, Privacy Policy and any additional terms and conditions listed as applicable to a particular scholarship shall be deemed an integral part of these Scholarship Rules. JAP Scholarship reserves the right to amend or discontinue scholarships and these Scholarship Rules at any time in its sole discretion.</p>
      <p style="font-size: 1rem;">Please note, if you are under 18, your parent or guardian must read and consent to these Scholarship Rules on your behalf.</p>
      <h3 class="wp-block-heading" style="font-size: 1.5rem;">1. GENERAL CONDITIONS</h3>
      <p style="font-size: 1rem;"><strong>Eligibility.</strong>&nbsp;You may apply for a chance to win a scholarship only if you meet the eligibility requirements set forth on the webpage for the particular scholarship. Additionally, scholarships are non-transferable and must be accepted as awarded and will not be paid to academic institutions outside of the United States. Without limiting the foregoing, you may not be an officer, director, member or employee of JAP Scholarship or any other party associated with the development or administration of the scholarship, or an immediate family member (i.e., parents, children, siblings or spouse) of any of the foregoing, or a person living in the household of any of these individuals, whether or not related. Further, JAP Scholarship reserves the right to disqualify any applicant from the scholarship in its sole discretion at any time.</p>
      <p style="font-size: 1rem;">Void where prohibited.</p>
      <p style="font-size: 1rem;"><strong>Application.</strong>&nbsp;No purchase or payment is necessary to apply for scholarships. Applicants must meet the scholarship’s eligibility requirements, submit a complete application through JAP Scholarship or the partner website by the application deadline, and agree to be bound by these Scholarship Rules. JAP Scholarship expressly reserves the right to disqualify any applicant and/or applications that are inaccurate, incomplete, or that JAP Scholarship believes in good faith to be generated by an automated means or scripts or are the result of plagiarism.</p>
      <p style="font-size: 1rem;"><strong>Selection.</strong>&nbsp;Accepted scholarship applications will be reviewed by representatives of JAP Scholarship or the scholarship sponsor to determine the winner of each scholarship. All decisions regarding the scholarship, including without limitation the selection of the winner, shall be final and binding in all respects. JAP Scholarship reserves the right not to award a scholarship if, in its sole discretion, it does not receive any qualified applications.</p>
      <p style="font-size: 1rem;"><strong>Notification.</strong>&nbsp;Scholarship recipients will be notified via the contact information provided to JAP Scholarship during the application process. Scholarship recipients may be subject to verification of eligibility and must be, at all times, in compliance with these Scholarship Rules. Although information that you provide may be verified, JAP Scholarship is not under any obligation to verify any of the information that you provide, and you hereby warrant that all information that you provide in your application and otherwise in connection with the scholarship is complete and accurate. If an award notification is returned as undeliverable or a potential winner does not supply the required verification within the time specified, the award will be forfeited and may be awarded to an alternate recipient at JAP Scholarship&#8217;s sole discretion.</p>
      <p style="font-size: 1rem;"><strong>Awarding.</strong>&nbsp;After successful notification of a scholarship award and verification, JAP Scholarship will provide payment of the award to the scholarship winner’s accredited academic institution to be applied towards tuition after receiving proof of enrollment, or by check. Unless otherwise stated, no scholarship monies will be paid directly to the winner.</p>
      <p style="font-size: 1rem;"><strong>General Terms.</strong>&nbsp;Scholarship recipients, by acceptance of their award, agree to release JAP Scholarship, its employees, representatives, agents, contractors, assigns, advertisers, and officers from any and all liability, loss, damage, cost, claim arising out of their participation in the scholarship. JAP Scholarship reserves the right to modify or terminate scholarships at any time for any reason in its sole discretion, with or without notice. The scholarship winner is solely responsible for any state or federal tax liability in association with acceptance of a scholarship. If any provision of the terms and conditions of a scholarship or these Scholarship Rules shall be held void, voidable, or unenforceable, the remaining provisions shall remain in full force and effect. JAP Scholarship is not affiliated with, sponsored by, or endorsed by any academic institution.</p>
      <br>
      <p style="font-size: 1rem;"><em>Last Updated: </em>August 28, 2023</p>
    </div>
  </main>

@endsection
